### PR TITLE
Create basic AccountsModel

### LINKED ISSUE #153: List accounts configured in EDS
The main view is currently empty. Instead it should list any accounts configured in EDS

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #153 

Do the least to get a list of supported accounts configured in EDS

### CODE REVIEW

**Comment by marbetschar** [comment]
I wonder if its easier to use one `E.SourceRegistryWatcher` with `E.SOURCE_EXTENSION_COLLECTION`. This way we only get the root `E.Source`, but not all task lists / event calendars underneath.

We probably need an additional `E.SourceRegistryWatcher` with `E.SOURCE_EXTENSION_MAIL_ACCOUNT` as well.

**Comment by danrabbit** [comment]
@marbetschar I'm not attached to this particular solution. If you think you know an easier way, then feel free to take over :)

**Comment by marbetschar** [comment]
@danrabbit  calendar and task lists are listed as accounts on my end (Screenshot below). Will try to refactor using the `E.SourceRegistryWatcher` so we can see if that works better. Other than that, it looks really nice! :)

Screenshot from 2021-05-26 19-32-34

**Comment by marbetschar** [comment]
@danrabbit now using `E.SourceRegistryWatcher`. The result looks much better, don't know how to filter "On This Computer" and "Search Folders" for mail accounts yet. We can iterate on this in another branch. Here's how it looks:

Screenshot from 2021-05-26 20-34-46

**Pull request merged**
