### PR TITLE
Spelling: Settings for online accounts

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by danrabbit** [comment]
This is the name of the component as it appears in AppCenter, not a link. So this change doesn't really make sense :)

**Comment by comradekingu** [comment]
@danrabbit Should it then not be `“Online Accounts” settings…`? I can't remember why I added the …

**Comment by danrabbit** [comment]
We don't currently have a convention of adding quotation marks here. None of the other system settings panes or indicators do this

**Comment by comradekingu** [comment]
@danrabbit
I could at least give some pointers in the context field on Weblate, but for some reason I only have access to nb_NO, which just prevents me from doing all sorts of stuff. https://l10n.elementary.io/user/kingu/ is my account if that is possible.
Just things like opening comments and having to change to my language to answer is meh. Everyone having access to all languages is way better IMO.

Technically "Online-account settings" is the correct way to do it.
Otherwise there is no distinction between "account settings done online" and "Account settings for online accounts".
Is a version of the latter possible?

I think the convention is to go "Dock" and "Mail", so "Online Account settings" would do, but then this has to be title case?

**Comment by danrabbit** [comment]
I'm not sure I understand what you're trying to say. This is the settings pane for online accounts. This is a page in system settings. The way it is written out currently is correct as is in US English

**Pull request closed without merging**
