### PR TITLE
CaldavDialog: use Adw.NavigationView

### PR DESCRIPTION
**Pull request by danirabbit**
replaces deprecated Leaflet

### CODE REVIEW

**Comment by ryonakano** [comment]
@danirabbit Could you resolve conflicts and explicit that we now require libadwaita-1 >= 1.4 in README and meson.build?

**Comment by danirabbit** [comment]
@ryonakano done!

**Review by ryonakano — COMMENTED** [review]
Works as expected, but maybe the same memory leak discussed in #283 happens here too…? :weary:

**Comment by danirabbit** [comment]
@ryonakano should be fixed now!

**Review by ryonakano — APPROVED** [review]
Nice!

**Pull request merged**
