### PR TITLE
Nextcloud Provider Support

### PR DESCRIPTION
**Pull request by marbetschar**
Draft pull request for Nextcloud support in Online Accounts. Next steps to consider:

- [ ] **WIP:** User needs the possibility to enter the Nextcloud server url before we try to login with OAuth
- [ ] The Integration.vala needs to be modified to whatever the Nextcloud OAuth flow expects
- [ ] The Nextcloud services Tasks, Calendars and Contacts need to be properly configured (what are the allowed BackendNames?)

### CODE REVIEW

**Comment by marbetschar** [comment]
Since we are using the Nextcloud Desktop Client's OAuth Client ID and Secret, I asked for clarification if dedicated keys for elementary OS should be created: https://help.nextcloud.com/t/how-to-request-a-well-known-oauth-client-id-and-secret-for-elementary-os/69469

**Comment by marbetschar** [comment]
@tintou can you please advise if the following works?

**The goal is to allow a user to enter a Nextcloud server URL and use this user defined URL in the subsequent OAuth authentication flow:**

1. **Add `<setting name="AskNextcloudURL" type="boolean">true</setting>` node** as first chlid node within `<group name="oauth2">` of the [nextcloud.provider.in file](https://github.com/marbetschar/switchboard-plug-onlineaccounts/blob/provider-nextcloud/providers/Nextcloud/nextcloud.provider.in)
2. **Define `OnlineAccounts.Key.ASK_NEXTCLOUD_URL`** in [src/Authentification/RequestQueue.vala](https://github.com/elementary/switchboard-plug-onlineaccounts/blob/892517c88fe2dadbdde90e736b9b0595230c5ac9/src/Authentification/RequestQueue.vala)
3. **Create `src/Authentification/NextcloudURLDialog.vala`** based on `MailDialog.vala`
4. **Add `... else if (info.parameters.contains (OnlineAccounts.Key.NEXTCLOUD))`** in [src/Authentification/RequestQueue.vala](https://github.com/elementary/switchboard-plug-onlineaccounts/blob/892517c88fe2dadbdde90e736b9b0595230c5ac9/src/Authentification/RequestQueue.vala#L59)

**Comment by marbetschar** [comment]
tested my assumptions in code - does not work as expected, the NextcloudDialog is not shown. @tintou  what I'm missing here?

**Comment by tintou** [comment]
So I looked at it and there is a way to make it not Nextcloud-specific by adding an OpenID Connect configuration (which is a layer atop OAuth2). Nextcloud supports it and some other services too.

**Comment by marbetschar** [comment]
@tintou thanks for the analysis. I did some digging, but was not able to found anything OpenID Connect related in [`libaccounts-glib`](https://gitlab.com/accounts-sso/libaccounts-glib) or [`libsignon-glib`](https://gitlab.com/accounts-sso/libsignon-glib). However, I found the below, non-completed issues in other `accounts-sso` related projects. Unfortunately I'm neither a C nor a C++ developer. That said, what's the suggested way forward from here on?

**Open issues related to OpenID Connect:**

- [signon-plugin-oauth2: merged #25](https://gitlab.com/accounts-sso/signon-plugin-oauth2/-/merge_requests/25)
- [signon-plugin-oauth2: issue #13](https://gitlab.com/accounts-sso/signon-plugin-oauth2/issues/13)

**and/or:**

- [gsignond-plugin-oa: issue #10](https://gitlab.com/accounts-sso/gsignond-plugin-oa/issues/10)

Not sure what the difference between `signon-plugin-oauth2` and `gsignond-plugin-oa` is though.

**Comment by marbetschar** [comment]
@tintou going further, shall we bet on OpenID Connect beeing available eventually for Nextcloud or implement it however GNOME Online Accounts does it?

I did not really figured out how it's done there, but as far as I remember it correctly it's available and stable for quite a while now.

Or maybe I'm totally missguided here - if so, please enlighten me 😅

**Comment by marbetschar** [comment]
@danrabbit is there already a suggested way of asking the user for a Server URL (either in code or conceptually), or is it not yet defined for `switchboard-plug-onlineaccounts` ?

Asking for the Nextcloud integration.

**Comment by jeremypw** [comment]
Gnome Online Accounts pops up a dialog with two entries for server address and username.

**Comment by marbetschar** [comment]
> Gnome Online Accounts pops up a dialog with two entries for server address and username.


@jeremypw it seems the auth flow is configured via XML. But I can't figure out how to ask for server url there.

**Comment by arkraft** [comment]
@tintou added a new PR which contains a new dialog with an URL entry (#139). Maybe the same could be applied to the Nextcloud  dialog.

**Comment by marbetschar** [comment]
Started to work on this again in the `nextcloud` branch, but get a `GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.MethodNotKnown: authentication method 'oauth' doesn't exist` error. I assume because [`gsignond-plugin-oauth`](https://gitlab.com/accounts-sso/gsignond-plugin-oa) is not installed.

And although I can see the package in the [Daily PPA](https://launchpad.net/~elementary-os), I'm not able to install it. @tintou are the `gsignond` packages not available for Odin yet?

**Comment by tintou** [comment]
@marbetschar you need to kill `gsignond` after the plugin installation

**Comment by jeremypw** [comment]
I think this can be closed now as it was targeted at Juno.

**Pull request closed without merging**
